### PR TITLE
Solar Orbiter Metakernels

### PR DESCRIPTION
**Pull request by rlaker**

### CODE REVIEW

**Comment by dstansby** [comment]
This is awesome, I did not know about metakernels (and spent about half a day individually tracking down all the bits for a full Orbiter set the other week), and am super keen to include this!

To make reviewing/merging this easier I'd suggest this is split into two PRs:
1. Searching for and downloading metakernels and the kernels they specify
2. Loading metakernels and the kernels they specify

I imagine 2. won't be too hard, but 1. might need a bit of thought in terms of user interface design.

**Comment by rlaker** [comment]
Ok great! I am happy to alter the code to achieve these two points. We can consider this PR the one where files are downloaded, since the other should be quite simple. This would also be applicable for BepiColombo too, I believe. 

For the first point, I was unsure how best to go about it, I think there are four possible options:
1. Download a [.zip](https://www.cosmos.esa.int/web/spice/solar_orbiter) file of all the files needed for a metakernel. This is quite a big file, and I think it gets larger with each update.
2. Clone the [git repository](https://repos.cosmos.esa.int/socci/projects/SPICE_KERNELS/repos/solar-orbiter) for the metakernel. This would stop really large downloads after the first clone. But would need interaction with git, which might defeat the point of implementing in this package.
3. Have a folder for each metakernel, so the user could swap between them easily.
4. (the method I tried with this PR) Download the metakernel file, and then download all the files it specifies separately, copying the folder structure needed by the metakernel. The advantage of this is that if the file already exists, then astrospice will not try and download it again, saving a lot of time. Two different metakernels could access the same file, so point 3 might not be necessary, but it might end up with many files in these folders.

Let me know what you think.

**Comment by dstansby** [comment]
As far as I can tell SPICE files don't change their contents, ie. a given file with a given filename is never updated, and updates are done by creating new files with new filenames. As such I don't think using a versioning system (ie. git) to download files would help.

I also don't think there needs to be a folder per metakernel, as the metakernels are just a list of files. Files could be duplicated between different metakernels, so there's no point keeping two copies of the same file.

So, I think approach 4) is the right one to take. I'll have a read of the code and leave some comments.

**Comment by dstansby** [comment]
Now the other PR is merged, you should be able to rebase this on top of the currently `main` branch. Give me a shout when this is ready for me to look at!

**Comment by dstansby** [comment]
Sorry for taking so long to come back to this. I'm trying to review it, but it looks like the rebase/merge has gone wrong somewhere and stuff is showing up in the diff that's already in the main branch. I tried rebasing this on to the main branch, but resolving the conflicts was a bit of a nightmare. 

As such I'd suggest starting again with a new git branch (branching of the current main branch), copying across all the new bits to that branch, and opening a new PR. How does that sound? If you don't have time to do that I can have a go myself, just let me know. Sorry about that, but it's pretty tricky to review this as it stands.

**Comment by rlaker** [comment]
I can do that, no problem

**Comment by rlaker** [comment]
Moved to #23

**Pull request closed without merging**
